### ISSUE TITLE
typescript porting question

### ISSUE THREAD

**Issue by ziriax** [SodiumFRP/sodium#85] opened 2016-03-03 13:52 UTC
Mainly for fun and to understand the code-base in depth, I started porting the c# version of sodium to Typescript.

Now, the Node class uses a WeakReference to the action. 

Unfortunately Javascript does not have weak refs yet... The ES6 WeakMap is also not suitable for implementing weak even listeners.

https://esdiscuss.org/topic/weak-event-listener

Would it be ok to require an explicit unlisten call to cleanup memory, as in RX?

**Comment by jam40jeff** [comment] 2016-03-03 15:07
I believe this would open the door to memory leaks.  I am actually not a fan of exposing `ListenWeak` in the public API (interestingly enough, it's only exposed for `Stream<T>` and not for `Cell<T>`) because I think users should always have to call `Unlisten` (or `Dispose` in C# will have the same effect) to deregister the listener.

However, the problem is with listeners created by the primitives themselves.  The primitives return a new `Stream<T>` or `Cell<T>` which may be disposed, which will in turn deregister the implicit listener they created.  However, these primitives are often chained, which means user code never gets a reference to them and they go out of scope very quickly.  The only thing holding a reference to them is the listener, stream, or cell at the end of the chain.  When the object at the end of the chain is freed up by calling `Unlisten`, the garbage collection is free to flow up the chain until we reach another stream or cell that is being held on to by user code because of the `WeakReference`s.

Here is an example of where I believe there would be a problem:

```c#
public class Test
{
    private readonly Stream<int> stream = Stream.Never<int>();
    private IListener listener;
    
    public void StartListenTest()
    {
        this.listener = stream.Map(_ => Unit.Value).Listen(_ => Console.WriteLine("It fired!"));
    }
    
    public void StopListenTest()
    {
        this.listener.Dispose();
    }
    
    public static void RunTest()
    {
        Test test = new Test();
        test.StartListenTest();
        test.StopListenTest();
        // At this point, test.listener should be cleaned up, but the listener created by the call to Map
        // will not be unless it was created with a WeakReference because test.stream will still hold
        // a reference to it.  There is no way to deregister that listener until test.stream (and thus,
        // test itself) goes out of scope.
        Thread.Sleep(5000);
        // now everything will get cleaned up (eventually when the GC gets to it) when this method
        // exits and the test variable goes out of scope
    }
}
```

**Comment by Ziriax** [comment] 2016-03-03 15:38
I don't know yet how Sodium works yet internally, but in Reactive Extensions, if you have code like:

`stream.Map(_ => Unit.Value).Listen(_ => Console.WriteLine("It fired!")).UnListen()`

then the tail `Unlisten` call will also unlisten from the original stream.

So your code in Reactive Extensions would not leak memory, even though no weak references are used here.

I will have to look at the code of `Map` and the other operators to understand why this is not the case in Sodium.

I guess this is because in Sodium (as in Flapjax) all signals are 'hot', so `stream.Map` immediately starts listening to stream. While in RX, `stream.Map` merely builds a new `IObservable` that will start listening to its input whenever someone listens to its output, and it will stop listening as soon as the output is not observed anymore. This is actually a simplified version: an operator like Map is an observable that when subscribed too will subscribe to its input, and return that disposable subscription. So RX does not have a Map 'node' that can have multiple listeners, it always delegates listening to its input. The 'node' is created on the fly when you call subscribe.

**Comment by jam40jeff** [comment] 2016-03-03 15:50
You are correct that the "node" is not created until the observable is observed in Rx.  In Sodium, the intermediate primitives begin listening right away.  I believe this may be necessary for the topological sort which allows for the glitch-free merge implementation, but I am not sure.  That would probably be a better question for @the-real-blackh.

**Comment by jam40jeff** [comment] 2016-03-03 16:00
FWIW, I just ran a test using Rx and it does in fact seem as if the intermediate operators are independent, which would not allow for a glitch-free implementation.

Given the following code:

```c#
[Test]
public void TestTwoListeners()
{
    Subject<int> s = new Subject<int>();
    IObservable<int> mappedS = s.Select(v => 2 * v);
    List<int> @out = new List<int>();
    IDisposable s1 = mappedS.Subscribe(@out.Add);
    IDisposable s2 = mappedS.Subscribe(@out.Add);
    s.OnNext(2);
    s.OnNext(7);
    s1.Dispose();
    s2.Dispose();
}
```

The code in the `Select` operator will run twice for each call to `OnNext` on the subject `s` because there are two subscriptions.

**Comment by Ziriax** [comment] 2016-03-03 16:55
In RX, you must do the sharing explicitly, like this:

```
[Test]
public void TestTwoListeners()
{
    Subject<int> s = new Subject<int>();
    IObservable<int> mappedS = s.Select(v => 2 * v).Publish().RefCount();
    List<int> @out = new List<int>();
    IDisposable s1 = mappedS.Subscribe(@out.Add);
    IDisposable s2 = mappedS.Subscribe(@out.Add);
    s.OnNext(2);
    s.OnNext(7);
    s1.Dispose();
    s2.Dispose();
}
```
`x.Publish()` only makes a single subscription to x, keeping its own list of subscriptions.

`x.RefCount()` does referencing counting on published subscriptions, releasing the input subscription when the last output subscription is disposed, what is exactly what you said :)

**Comment by jam40jeff** [comment] 2016-03-03 17:08
Implementing similar reference counting logic would seem to work for discrete streams and cells which are "observed" using `Listen`, but I am not sure if it would suffice for the "continuous" case where a cell is sampled at a time interval.

**Comment by Ziriax** [comment] 2016-03-03 17:55
Sample is the pull interface I guess, where Listen is the push?

Why not have a Sampler object that increments the refcount and releases when disposed? So instead of Sample returning a value, it returns a Sampler object that allows sampling and can be disposed.

That looks a lot to .NET's IEnumerable and IEnumerator of course...

**Comment by jam40jeff** [comment] 2016-03-03 18:20
I like that idea.  It would permit a more deterministic deregistration of listeners even in other languages as well as the ability to make other optimizations such as not running the logic for the intermediate primitives unless a downstream listener or sampler is attached.

However, I would like to hear @the-real-blackh's opinion on this as he knows the ins-and-outs of the Sodium code much better than I do.

**Comment by the-real-blackh** [comment] 2016-03-03 18:55
One of the reasons why weak references are needed is the situation where you have a Stream or Cell waiting in some logic that will some time in the future output a Cell<Stream<A>> or Cell<Cell<A>> that is then switched. It has no listeners, but it - and the chain of other Stream/Cells that lead to it - need to be kept alive just from a reference to it held inside a lambda. This can only be tracked through the language, as it were, not directly.

So, I can't see any way around the requirement for weak references.

**Comment by ritschwumm** [comment] 2016-03-03 19:11
btw, weak refs can lead to interesting problems when your dependency graph changes often and the garbage collector does not remove obsolete nodes fast enough so they keep calculating useless stuff for longer than necessary.

**Comment by the-real-blackh** [comment] 2016-03-03 19:20
ritschwumm: This would cause performance degradation in Sodium but no incorrect answers, so no "problems" as such.

**Comment by ritschwumm** [comment] 2016-03-03 19:34
@the-real-blackh so i thought. still annoying when you run into it. seems like a 'real' solution would require a different garbage collector ala http://tomasp.net/academic/papers/hollywood/hollywood.pdf .

**Comment by Ziriax** [comment] 2016-03-03 19:47
So higher order signal trouble, it keeps biting me ;-)

Could you give an example? It would help me understand this better. 

Because weak references are not part of Javascript yet, it does not make sense to port Sodium to Typescript.

But maybe we don't need real weak references to implement SodiumJS, but just WeakMap. But I doubt it, and to be honest I don't understand WeakMap yet, it feels like a strange beast, since it are the keys that are weak, not the values...

**Comment by jam40jeff** [comment] 2016-03-03 20:08
@the-real-blackh, I may not be following, but it seems like "something" in scope would have to hold a reference to the switched stream or cell, right?  If so, it would be kept alive by that reference (and by virtue keep all of its upstream streams and cells alive).  I believe the only problem the weak reference solves is not keeping the upstream streams and cells from keeping downstream ones alive.  This could still be done manually through listener/sampler counting if that link is broken once the count reaches 0 and reattached when it goes above 0.  This would mean the upstream stream or cell would no longer keep the switched one alive, but any other reference still could (and the refcounting logic would mean it still could "reattach" if something listens to it again).

**Comment by the-real-blackh** [comment] 2016-03-03 20:25
```java
Cell<A> a1 = ...;
Cell<A> a2 = ...;
Stream<Unit> sChange = ...;
Cell<A> a = Cell.switchC(sChange.map(u -> a2).hold(a1));
```
In this example we'd need to make sure the lambda `u -> a2` kept a2 alive.

I don't know from direct experience of WeakMap in Javascript, but I think it can be done with WeakMap. All we need to do is 1. track whether any references to something exists, and 2. run a finalizer when no more references to it exist.

* Give each Cell/Stream a unique ID.
* Store a 'tracker' object containing the unique ID as the key of the WeakMap.
* Also use the unique ID alive in a normal map called 'finalizers' mapping to lambdas that clean things up.
* Retain the 'tracker' object inside the Cell/Stream so that whenever it is referenced, the tracker is kept alive in the WeakMap.
* Periodically compare the 'trackers' weak map against the 'finalizers' map. If any key exists in 'finalizers' but not 'trackers', then run the finalizer code and remove the entry from 'finalizers'.

A potential problem is that if there is a long chain of these, it could take many repeats of this to clean everything up. However, this can be fixed by calling these 'implicit trackers' and also having explicit ones not based on WeakMap for the more common case where we can track the reference directly. You'd have to deal with cycles. That could be done either by using both kinds of trackers at once, or by explicit cycle detection. Both schemes would work. The first is probably easiest.

**Comment by the-real-blackh** [comment] 2016-03-03 20:30
I've just realized that the 'potential problem' above is not a problem as long as trackers reference their dependents directly and not through finalizers.

**Comment by ritschwumm** [comment] 2016-03-03 20:47
i don't see how you could compare the two key sets - there's no way to iterate over the keys or entries of a WeakMap.

**Comment by the-real-blackh** [comment] 2016-03-03 20:48
That could be a show-stopper.

**Comment by jam40jeff** [comment] 2016-03-03 20:50
In the example, the lambda should keep `a2` alive through the closure.  The closure should be kept alive by the result of `map`.  The result of `map` should be kept alive (eventually) by `switchC`.  The result of `switchC` should be kept alive by `a`.

**Comment by the-real-blackh** [comment] 2016-03-03 20:51
Yes, that's right.

**Comment by Ziriax** [comment] 2016-03-03 21:17
So, does that mean that the referencing counting approach might be worth trying?

I hope it doesn't give problems with feedback loops... Cyclic references...

**Comment by the-real-blackh** [comment] 2016-03-03 21:23
Unfortunately reference counting isn't going to work because in the example I gave...
```java
Cell<A> a1 = ...;
Cell<A> a2 = ...;
Stream<Unit> sChange = ...;
Cell<A> a = Cell.switchC(sChange.map(u -> a2).hold(a1));
```
...lambdas are opaque, so there's no way for the reference counting algorithm to introspect to see whether the lambda refers to a2 or not.

**Comment by the-real-blackh** [comment] 2016-03-03 21:27
Maybe I'm missing something, but as far as I can see, "true" FRP can't be implemented in Javascript as long as there's no finalizer capability. This is worth lobbying Javascript standards people over, IMO.

**Comment by jam40jeff** [comment] 2016-03-03 22:43
@the-real-blackh, I should be using a different terminology than "reference counting"; maybe "listener counting".  In your example, the lambda would prevent `a2` from being garbage collected.  The fact that there are no listeners means that the "listener counting" algorithm will disconnect `a2` from its upstream parents so they are not the cause of keeping `a2` alive in the case that the lambda goes out of scope (which can only happen in this case if `a` goes out of scope).  However, `a2` will be reattached as soon as its "listener count" goes above 0, which will happen when it is switched to by `switchC`.

The challenge I see is that cells which have no listeners will detach from their upstream parent.  They will later reattach if needed when a listener is added, but this would require the Stream -> Cell transition (only `hold` I believe?) to be able to "replay" the last value from the upstream Stream object since it wasn't listening while its "listener count" was 0 and doesn't have an up-to-date current value.

**Comment by the-real-blackh** [comment] 2016-03-03 23:07
I see exactly what you mean! You're onto something, and maybe this can be solved.

I agree that tracking `hold`s should be the only issue here, and since we only need the last value, maybe it can be solved by making all streams remember one previous value. This would mean that the implementation would become a push/pull model, but that is fine.

We still have to solve cycle collection, but we have all the tracking information we need, so it can be done. Your insight means that the Javascript problem and the C++ problem (which I'm trying to solve) are the same.

For the cycle collection, I think somewhere in this paper is the algorithm we need:

http://researcher.watson.ibm.com/researcher/files/us-bacon/Bacon03Pure.pdf

**Comment by the-real-blackh** [comment] 2016-03-03 23:10
Actually the Javascript problem and the C++ problem may not be quite the same because there's no garbage collector at all in C++ and so the reference held inside a closure has to be managed by reference counting and so it could form part of a cycle. In Javascript this would always be outside the cycle. (I could be wrong about this.)

**Comment by ritschwumm** [comment] 2016-03-03 23:36
wait a minute. isn't disconnecting-from-upstream a problem for *all* stateful combinators?

**Comment by the-real-blackh** [comment] 2016-03-03 23:39
`hold` is the only stateful combinator.

**Comment by ritschwumm** [comment] 2016-03-03 23:48
oh.. i'd have expected a combinator like 
((S,T) => (S,U)) => S => Stream[T] => Stream[U]
that advances an internal state S for each new T and additionally emits an U calculated from the previous S and the T. could this be implemented in terms of hold?

**Comment by the-real-blackh** [comment] 2016-03-04 00:21
All of those are written in terms of hold. Actually `lift` is another combinator that would be affected by these issues but the solution is no different to what we'd do with `hold`.

**Comment by Ziriax** [comment] 2016-03-04 08:12
How does David Sankel solve this in his SFRP C++ library?

I think he also has a denotational semantic

Or maybe he has memory leaks, could be.

I see in your DS that switch always trims the signal it is switching into. Doesn't that make switching very expensive? Because it means that all the signals you will eventually switch in to are all running. It would also mean that if I inline the `a2` in your example, that I would get different behavior. Doesn't that mean that referential transparency is broken? Or should I read this code in a monadic way, and inlining creates a completely different monad, and so referential transparency is not  broken at all. And by creating a signal in a lambda you can also make switching efficient. That does make sense, the construction of a signal also starts it, just like the JavaScript interval function also starts (but that is IO monadic ofcourse so your code must run all in a monad, and I just answered my own question)

But indeed that approach seems to require a garbage collector... 

I might be completely wrong, just trying to understand. I will experiment more with the library to get a better idea of it.

**Comment by Ziriax** [comment] 2016-03-04 08:18
Flapjax is written in Javascript and has a similar semantic I think. So I am curious how they tackled this problem

**Comment by HeinrichApfelmus** [comment] 2016-03-04 09:07
@jam40jeff I'm afraid it's not that simple. If you want to discard `a2`, then you have to make sure not just that no one is listening to it, but that no one will *ever be able* to listen to it *again*. Otherwise, you have to update the state inside `a2` as usual, because it's not possible to reconstruct the value once you've discarded it. To fulfill the latter condition, you need support from the language runtime in the form of garbage collection.

@Ziriax I have taken a cursory look at Flapjax, and from the description in their paper, it appears to me that their combinator for merging event streams (I like to call it `unionWith`)) is *not* deterministic. I hope I'm not wrong here, but this essentially brings it to the same level as the React* family of libraries.

That said, the issue with garbage collection is probably orthogonal to the deterministic merge problem. I have no idea what Flapjax does there.

**Comment by Ziriax** [comment] 2016-03-04 09:47
- Regarding `WeakMap` 

The `WeakMap` is intriguing. I can see how it helps to associate private data to say a DOM node `n`. First private data is associated to node `n` by using `weakmap.set(n, data)`. Then you attach an event handler to `n`, and that handler will lookup the data from the weakmap. If `n` is deleted, and no further references exist to `n`, the weakmap will delete the key-value automatically. This is very useful to extend immutable objects with data without leaks. Somehow it feels that this should be enough to solve the problem here.


- Regarding non-determinsm

As far as I understand it, the garbage collector now also introduces another form of non-deterministic behavior, because signals are only stopped when garbage collected? So a composite signal like `let s = windowAnimationFrameEvent(moment).map(gameLevelState)` might perform the potentially very expensive computation `gameLevelState` for a long time until `s` is garbage collected? And the theoretical `windowAnimationFrameEvent` will unsubscribe from the external `animationFrame` event in its finalizer?  

I mean non-determinism not in the form of results being computed, but computational resources being wasted.

So FRP makes not only the space  garbage collection non-deterministic, but also the time. And somehow writing it like this does make sense, because if garbage collection would be instantaneous, both the space and time non-determinism would go away. We need hardware garbage collection :)

**Comment by jam40jeff** [comment] 2016-03-04 13:20
@HeinrichApfelmus I came to that conclusion last night after implementing the attach/reattach logic for streams, unfortunately.  For cells, the entire upstream history must always be stored since some combinators (such as `accum`) need to replay all missed values rather than just the latest.

**Comment by Ziriax** [comment] 2016-03-05 07:39
Could the problem be solved by introducing a `Seq` operator that has the following semantics:

`x.Seq(y)` means that whenever `x` is started (listened to), `y` is also started.

This would change the semantics of the FRP system of course...

So Stephen's example:

```
Cell<A> a1 = xxx...;
Cell<A> a2 = yyy...;
Stream<Unit> sChange = zzz...;
Cell<A> a = Cell.switchC(sChange.map(u -> a2).hold(a1));
```

Would become

```
Cell<A> a1 = xxx...;
Cell<A> a2 = yyy...;
Stream<Unit> sChange = zzz...;
Cell<A> a = Cell.switchC(sChange.seq(a2).map(u -> a2).hold(a1));
```

Without the `seq`, the behavior of the code snippet would be the same as if a2 was inlined in the lambda: `u -> yyy...`, meaning it would only start as soon as `sChange` fires, not when `a` is listened to.

Maybe this kills all of the semantics, but if not, I think it might allow reference counting, but it's just an intuition...

**Comment by Ziriax** [comment] 2016-03-05 07:56
Maybe `co` is a better name than `seq`, as it has a different meaning than Haskell's `seq`

So `x.co(y)` means `y` is started resp stopped together with `x` at the first resp last `listen`

**Comment by jam40jeff** [comment] 2016-03-05 20:49
This would kill the semantics.  Any cells in the chain would miss events when there are no listeners, so they will hold an invalid value if anyone attempts to listen on them at a later point.

At first I thought this could be solved by replaying the last event on listen, but I didn't take into account accumulators or filters, which would require replaying more than just the last value to ensure the current cell value is reconstructed accurately.

**Comment by Ziriax** [comment] 2016-03-06 13:41
Indeed, mea culpa.

This is unfortunate, so an Ecmascript version will have to wait until weak refs *with finalizers* are supported.

**Comment by jam40jeff** [comment] 2016-03-06 14:13
In the C# version, I do not use finalizers.  I only remove a node from its
parent the next time the parent stream fires (and finds a stale
WeakReference).

**Comment by the-real-blackh** [comment] 2016-03-07 19:53
@jam40jeff For cells, the entire upstream history must always be stored since some combinators (such as accum) need to replay all missed values rather than just the latest.

I fear that you are correct, and this means it can't be done in Javascript now. Remembering all previous updates is not going to work, because the objective is to prevent memory leaks.

The C# way you describe is of course fine but is effectively the same as a finalizer so it doesn't help.

The problem is to track what is referenced and what isn't. The 'co' operator would sort of work, but it would place an unpleasant burden on the writer of the code.

```java
Cell<A> a = Cell.switchC(sChange.co(a2).map(u -> a2).hold(a1));
```

I only spent about 30 minutes reading David Sankel's code. I don't think he deals with this problem. I also don't think Flapjax does either. I found out from using it that Rx.JS suffers from the same leak (no surprise there).

In the v2 of sodium for C++ I am attempting to use some black magic called MagicRef to track what a std::function refers to. Basically I run all copy constructors under the control of some global variables that track what reference counts are altered when the std::function is copied. The assumption is that all reference counting variables are MagicRefs and never std::shared_ptrs. Whether this works or not will be dependent on the implementation of the compiler. If std::function uses std::shared_ptr or equivalent internally, it won't work. This trick does work in GNU C++.

**Comment by Ziriax** [comment] 2016-03-07 20:11
An ambitious project would be to fork the Typescript compiler so that it generates the required code. After all, the TS compiler parses all functions and lambda's, so it could track all references to signals. Not sure if this is doable...

**Comment by the-real-blackh** [comment] 2016-03-07 20:34
I don't see any reason why modifying the Typescript compiler in this way wouldn't work, but I think it's fairly ambitious.

Could the '.co' thing be made to work? I can't see why not. All our dependencies are trackable except for the contents of lambdas. If it's possible for the FRP code writer to explicitly tag these dependencies, then it should solve it, as long as the person does it correctly. It's only an issue in relatively rare cases, and where the user fails to type it, in many cases the code will fail 100% of the time. Another possible name for it is '.dep' (for 'depends-on').

In the meanwhile, we lobby Javascript standards bodies.

**Comment by Ziriax** [comment] 2016-03-07 21:13
Good luck, I don't understand enough of the code-base yet to know if it will work :)

**Comment by Ziriax** [comment] 2016-03-17 11:25
According to someone at [Reflex FRP](https://github.com/reflex-frp/reflex/issues/34#issuecomment-197814785), GHCJS has its own system for tracking weak-references...

**Comment by the-real-blackh** [comment] 2016-07-06 21:56
In case anyone following this thread has missed it, I've implemented the scheme of explicitly declaring dependencies in lambdas in the Typescript version of Sodium and it seems to actually work! https://github.com/SodiumFRP/sodium-typescript

**Comment by jam40jeff** [comment] 2023-04-23 00:04
Closing as this has been implemented in TypeScript.

**Closed by jam40jeff** 2023-04-23 00:04 UTC
